version: '3.8'

services:
  config-storage:
    image: ghcr.io/omvmike/config-storage:aws
    entrypoint: config-storage
    environment:
      - AWS_OIDC_ROLE_ARN=arn:aws:iam::123456789012:role/role-name
      - AWS_BUCKET=test.boomr
      - PATH_PREFIX=config-storage/test
    volumes:
      - ./:/tmp
      - ~/.aws:/root/.aws