version: '3.8'

services:
  config-storage:
    image: ghcr.io/omvmike/config-storage:gcp
    entrypoint: config-storage
    environment:
      - GCS_BUCKET=cw-config
      - PATH_PREFIX=config-storage/test
      - GCP_KEY_FILE_PATH=/secrets/key.json
    volumes:
      - ./secrets:/secrets
      - .:/tmp
