name: Deploy to GitHub Container Registry

on:
  push:
    branches:
      - main
    # You can specify paths to only trigger on changes to certain files
    paths:
      - 'aws/Dockerfile'
      - 'aws/aws-config-storage.sh'
      - '.github/workflows/deploy-aws-container-to-ghcr.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/config-storage:aws
          # If your Dockerfile is not in the repository root, specify the path
          context: aws/

      - name: Verify deployment
        run: echo "Image deployed to GitHub Container Registry"

